### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by akshay1027** [FOSS-Cell-GECPKD/pixelvibe#103]
**description**
Add footer

**Comment by ankitapuri** [comment]
can u please elaborate , where to add footer

**Comment by avinal** [comment]
Also do specify the contents of the footer.

**Comment by akshay1027** [comment]
contents we can add to Footer are @avinal @ankitapuri  :
1)Find us 
2)Call us 
3)Mail us 
4)Website logo
5)What this website is about
6)Follow us
-Instagram link with logo
-LinkedIn link with logo
-Twitter link with logo
-etc
7)Useful links
-Home
-Services
-About Us
-Contact Us etc
8)Subscribe
-Email address
9)Copyrights
10) All the above with responsive UI

**Comment by simranbhalla3** [comment]
Hi , can i work on this issue?

**Comment by manisha-27** [comment]
I want to work on this issue.

**Comment by akshay1027** [comment]
I myself want to work on this, hence made the issue :)

**Comment by akshay1027** [comment]
any update on this?  @ankitapuri

**Comment by ankitapuri** [comment]
We don't need so detailed footer . It will occupy so much space . Moreover , we already have one PR for the same for the login page .
