### ISSUE TITLE
Add Dark/Light mode

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [FOSS-Cell-GECPKD/pixelvibe#104]
I can Add Light Dark Mode to all of the pages which adds another feature to this website and which just gives two choices to the user as what its preferable UI is either light or dark.

**Comment by Bhavya-Sehgal** [comment]
I want to work on this issue as GSSOC'21 participant. Please assign me this issue. @ankitapuri  @avinal

**Comment by ankitapuri** [comment]
we already have one on login page and Its not required on the main canvas page . Like it would be difficult to reuse the code again n again making it more complex .

**Comment by adarshvulli** [comment]
@Bhavya-Sehgal, I would like to close this issue. Cause we aldredy have our plans for the dark mode.
