### ISSUE TITLE
Change login page design

### ISSUE THREAD

**Issue by Avishake007** [FOSS-Cell-GECPKD/pixelvibe#107]
I want to change the login page design 
Please assign me for this task under gssoc'21

**Comment by ankitapuri** [comment]
> I want to change the login page design
> Please assign me for this task under gssoc'21

what design u suggest

**Comment by Avishake007** [comment]
I am thinking of working on box shadow, hover and background color of the login page.

**Comment by manisha-27** [comment]
Hey, can i work on this issue?

**Comment by ankitapuri** [comment]
> I am thinking of working on box shadow, hover and background color of the login page.

Any wireframe for the same ?
