### ISSUE TITLE
Color scheme of main page. 

### ISSUE THREAD

**Issue by ankitapuri** [FOSS-Cell-GECPKD/pixelvibe#109]
**Screenshots**

Working on the color scheme of index.html , to make it uniform across the website .

**Comment by rupal11** [comment]
I want to work on it

login.html and index.html
![2021-04-06_111406](https://user-images.githubusercontent.com/60324778/113664403-5135b800-96c9-11eb-944a-d921cb7697a2.jpg)
![login](https://user-images.githubusercontent.com/60324778/113664407-5266e500-96c9-11eb-970f-860f097c150c.jpg)

The login page is in blue color but the index page is pink color. So to maintain uniformity I want to change the color scheme.

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.
