### ISSUE TITLE
New Feature: Choice of Colour to Draw with

### ISSUE THREAD

**Issue by N-Shar-ma** [FOSS-Cell-GECPKD/pixelvibe#112]
I would like to give the user the option to pick a color with which they can draw on the canvas, so that they are not limited to using only black. A color input can be added for this beside the canvas element

**Comment by ankitapuri** [comment]
![image](https://user-images.githubusercontent.com/54734002/114888503-eb62d200-9e26-11eb-91df-622bd8a5831d.png)

**Comment by ankitapuri** [comment]
@N-Shar-ma  and @AtharvaKamble  u both want to work on it ?

**Comment by athkdev** [comment]
Hi @ankitapuri, yes will start working this issue.

**Comment by N-Shar-ma** [comment]
@ankitapuri Sorry for the late response, is there any way I can still contribute to this issue?

**Comment by ankitapuri** [comment]
> @ankitapuri Sorry for the late response, is there any way I can still contribute to this issue?

text me on discord once
