### ISSUE TITLE
website is not responsive

### ISSUE THREAD

**Issue by akshay1027** [FOSS-Cell-GECPKD/pixelvibe#118]
**Screenshots**
The Card can be made responsive, it would be very difficult to enter Numbers as the card is small here!

![2021-04-12 (2)](https://user-images.githubusercontent.com/65683151/114388481-5b682280-9bb1-11eb-9452-ec4c55b96ef0.png)

**Comment by akshay1027** [comment]
I would like to work on this @ankitapuri @avinal

**Comment by ankitapuri** [comment]
> I would like to work on this @ankitapuri @avinal

we have a PR for this problem
