### ISSUE TITLE
To change color of footer 

### ISSUE THREAD

**Issue by ankitapuri** [FOSS-Cell-GECPKD/pixelvibe#121]
**Screenshots**
To change color of footer in the login page according to the light and dark mode .

**Comment by SnehaVeerakumar** [comment]
I would like to contribute to this issue

**Comment by arpit456jain** [comment]
@ankitapuri there is also one more issue text is not in center 
<img width="960" alt="pix" src="https://user-images.githubusercontent.com/55352601/114678326-c25c1780-9d28-11eb-9f4d-c29e39d20d0d.png">


and overlapping in mobie view
<img width="960" alt="pix2" src="https://user-images.githubusercontent.com/55352601/114678455-dd2e8c00-9d28-11eb-8a56-995069c53753.png">


I would like to work on this issue and I will also resolved these two problems under this issue.

@ankitapuri kindly assign this issue to me .

**Comment by ankitapuri** [comment]
> @ankitapuri there is also one more issue text is not in center
> <img alt="pix" width="960" src="https://user-images.githubusercontent.com/55352601/114678326-c25c1780-9d28-11eb-9f4d-c29e39d20d0d.png">
> 
> and overlapping in mobie view
> <img alt="pix2" width="960" src="https://user-images.githubusercontent.com/55352601/114678455-dd2e8c00-9d28-11eb-8a56-995069c53753.png">
> 
> I would like to work on this issue and I will also resolved these two problems under this issue.
> 
> @ankitapuri kindly assign this issue to me .

I can create a separate issue for the same . but its first cum first serve so @SnehaVeerakumar shall be given a chance .

**Comment by arpit456jain** [comment]
@ankitapuri should i make a separate issue for this ??

**Comment by ankitapuri** [comment]
> @ankitapuri should i make a separate issue for this ??

sure

**Comment by SnehaVeerakumar** [comment]
I need to change the color of "made with <3" to white when the dark mode is turned on. Am I correct ? @ankitapuri

**Comment by ankitapuri** [comment]
> I need to change the color of "made with <3" to white when the dark mode is turned on. Am I correct ? @ankitapuri

yes

**Comment by SnehaVeerakumar** [comment]
@ankitapuri  yeah done ! Check my PR please.
