### ISSUE TITLE
[Preloader] 

### ISSUE THREAD

**Issue by archanagandhi** [FOSS-Cell-GECPKD/pixelvibe#125]
Hey @ankitapuri ,
I would like to add a animated PRELOADER to the website. Please assign this to me

**Comment by ankitapuri** [comment]
> Hey @ankitapuri ,
> I would like to add a animated PRELOADER to the website. Please assign this to me

hey @archanagandhi  , we already have a pre-loader but its a heavy css , so can u suggest some modifications

**Comment by archanagandhi** [comment]
Sure @ankitapuri . Do you want the same loader style or can I suggest a new one?

**Comment by ankitapuri** [comment]
> Sure @ankitapuri . Do you want the same loader style or can I suggest a new one?

if u can improve the exisiting one . If not , u can suggest new as well

**Comment by archanagandhi** [comment]
I had a look at the loader Ankitapuri. What I felt was the loader is too heavy. 
My suggestion is something a **Cube** like loader will matches our website( because we do pixel art ) Also looks simple and clean.
if you like it you can assign this to me. Also please tell your suggestions.

**Comment by ankitapuri** [comment]
Cool Archana , but can u show some live example like how u r gonna make it work

**Comment by archanagandhi** [comment]
https://user-images.githubusercontent.com/74424757/115134970-84196d80-a032-11eb-83e7-b83cd19091f0.mp4

Like this. we can use any color of your choice

**Comment by ankitapuri** [comment]
cool ! Just choose colors which suit with the existing webpage
