### ISSUE TITLE
Create Canvas.html

### ISSUE THREAD

**Issue by rupal11** [FOSS-Cell-GECPKD/pixelvibe#126]
I want to create a separate canvas.html.It will have CSS and javascript files linked to it and will be called when submit button on index.html is clicked.

Wireframe -

![wireframe](https://user-images.githubusercontent.com/60324778/114988604-24955380-9eb4-11eb-8bbc-43434625bf06.png)

The background will be pink in color as shown in index.html and the canvas will be white. 
There will be three sections :
-title
-canvas
-tools

I am not adding any tools.

**Comment by ankitapuri** [comment]
@rupal11 any update?
