### ISSUE TITLE
Enhancing user input.html page

### ISSUE THREAD

**Issue by CMELAKKIA** [FOSS-Cell-GECPKD/pixelvibe#127]
I would like to add different themes to the web page. I can also enhance the buttons and add hover effect.

**Comment by ankitapuri** [comment]
> I would like to add different themes to the web page. I can also enhance the buttons and add hover effect.

what themes @CMELAKKIA

**Comment by CMELAKKIA** [comment]
@ankitapuri  I will add three themes default dim(dark blue) and dark. I will also create color switchers which will change the color of icons and buttons based on the color that is picked. 
![image](https://user-images.githubusercontent.com/76167557/115137837-02333f80-a046-11eb-9a84-4cf5a2294673.png)

**Comment by ankitapuri** [comment]
> @ankitapuri I will add three themes default dim(dark blue) and dark. I will also create color switchers which will change the color of icons and buttons based on the color that is picked.
> ![image](https://user-images.githubusercontent.com/76167557/115137837-02333f80-a046-11eb-9a84-4cf5a2294673.png)

cool

**Comment by CMELAKKIA** [comment]
@ankitapuri please review my pr

**Comment by CMELAKKIA** [comment]
@ankitapuri I have changed the dim theme color from dark blue to bluish black in #139

**Comment by subhangi2731** [comment]
is this issue open can I work on this? @ankitapuri
