### ISSUE TITLE
Adding new feature

### ISSUE THREAD

**Issue by CMELAKKIA** [FOSS-Cell-GECPKD/pixelvibe#128]
@ankitapuri  I would like to add different sized pens.

**Comment by rish-singhal** [comment]
Can you please elaborate more? or some reference images?

What different sized pens would do?

**Comment by CMELAKKIA** [comment]
Adding different sizes of brushes will improve the feel of this project..
For example, having smaller, small, medium and big sized brushes.
![image](https://user-images.githubusercontent.com/76167557/115297469-dadd8f00-a179-11eb-9353-fe7cab0d5654.png)

**Comment by rish-singhal** [comment]
Currently, whenever we use a "default size" brushes it creates a 1x1 box. According to the new sized brushes you are suggesting, will it create 2x2, 3x3, .... box

**Comment by CMELAKKIA** [comment]
@rish-singhal  Yes

**Comment by rish-singhal** [comment]
@ankitapuri we can assign I guess?

**Comment by ankitapuri** [comment]
![image](https://user-images.githubusercontent.com/54734002/115497986-50388500-a28a-11eb-950b-ab53aa377749.png)

This is actually the layout , but before that we need a drop down menu and also these variable brush sizes should also appear in some drop side ways fashion

**Comment by rish-singhal** [comment]
@CMELAKKIA  any updates from your side?

**Comment by CMELAKKIA** [comment]
@rish-singhal i can make the brushes appear in drop down fashion

**Comment by ankitapuri** [comment]
> @rish-singhal i can make the brushes appear in drop down fashion

okay! Can u make a major menu above it

**Comment by CMELAKKIA** [comment]
@ankitapuri  Yes I would like to work on that.

**Comment by CMELAKKIA** [comment]
@ankitapuri  Can you assign this issue to me?

**Comment by arpit456jain** [comment]
@CMELAKKIA are you working on this issue ?

**Comment by CMELAKKIA** [comment]
@arpit456jain  Im having exams now so  it will take time for me to complete  . If you want to work on this i'll unassign myself.

**Comment by arpit456jain** [comment]
no @CMELAKKIA that's fine

**Comment by arpit456jain** [comment]
i was asking because i had done some major changes in canvas.html so if you were working on it you will surely face merge conflicts ...

**Comment by CMELAKKIA** [comment]
I will look into it when i start working on this

**Comment by subhangi2731** [comment]
@ankitapuri please assign me this issue
