### ISSUE TITLE
Index page is not responsive

### ISSUE THREAD

**Issue by gnikita432** [FOSS-Cell-GECPKD/pixelvibe#130]
**Screenshots**
![image](https://user-images.githubusercontent.com/61223163/115207398-30ce1a80-a119-11eb-8c39-6eb4bf1ed888.png)
I want to work on making the index page responsive  under gssoc

**Comment by rish-singhal** [comment]
seems good to me. What about you @ankitapuri ?

**Comment by ankitapuri** [comment]
> seems good to me. What about you @ankitapuri ?
I'll assign her
