### ISSUE TITLE
Create a forgot password page

### ISSUE THREAD

**Issue by gnikita432** [FOSS-Cell-GECPKD/pixelvibe#131]
**Screenshots**

**Comment by rish-singhal** [comment]
seems fine, I guess? @ankitapuri ?

**Comment by ankitapuri** [comment]
> **Screenshots**
> If applicable, add screenshots to help explain your problem.

Can u show a rough layout for the same

**Comment by gnikita432** [comment]
Yes, when the user will click on forgot password link on the login page, A card will pop up which will say to reset the password. The card will somewhat look like this
![image](https://user-images.githubusercontent.com/61223163/115323399-b1d2f380-a1a5-11eb-8a43-2e74ed60ad8c.png)
It will have the content like this and I will style the card according to the login page theme.

**Comment by gnikita432** [comment]
Hey, Should I create new files for login.css and script(login.js) of the login.html Or I include the script and css in login.html file only?

**Comment by rish-singhal** [comment]
@gnikita432 separate files will be good!

**Comment by gnikita432** [comment]
hey, can you please review the design of the card
![image](https://user-images.githubusercontent.com/61223163/115874585-e246b600-a461-11eb-98d6-26247ed4df95.png)

**Comment by gnikita432** [comment]
Hey, Can you please review the design
![image](https://user-images.githubusercontent.com/61223163/115878304-060bfb00-a466-11eb-8a8d-a5c2ef60c06c.png)

**Comment by ankitapuri** [comment]
Can you make that made with love bit centered
