### ISSUE TITLE
Add Prettier for code formatting

### ISSUE THREAD

**Issue by gnikita432** [FOSS-Cell-GECPKD/pixelvibe#133]
**Screenshots**

**Comment by rish-singhal** [comment]
Add Prettier for code formatting-- can you explain a bit more? @gnikita432

**Comment by gnikita432** [comment]
Installing and setting up prettier will help to format the code automatically on saving. Many contributor contributes to the project and may do some bad code formatting practices like adding unwanted extra space lines or not adding proper space so prettier will be useful for perfectly structured and easy to read code. Prettier will follow one pattern and format the code accordingly on saving. basically Prettier is an opinionated code formatter. It enforces a consistent style by parsing your code and re-printing it with its own rules that take the maximum line length into account, wrapping code when necessary. 
More info: https://prettier.io/docs/en/why-prettier.html

**Comment by ankitapuri** [comment]
@gnikita432  using prettier is a lot space-consuming which we need to avoid at this point of time . 
We might reconsider it later . so u can close the issue as of now
