### ISSUE TITLE
Add hover effect on pick a color

### ISSUE THREAD

**Issue by gnikita432** [FOSS-Cell-GECPKD/pixelvibe#142]
**Screenshots**
![image](https://user-images.githubusercontent.com/61223163/116784550-7217e000-aab2-11eb-8367-01e2a4ebbb45.png)
I would like to add some hover effect on the focus effect on the colors.

**Comment by ankitapuri** [comment]
Can you please elaborate @gnikita432

**Comment by arpit456jain** [comment]
are you working on this issue @gnikita432 ??

**Comment by gnikita432** [comment]
No @arpit456jain you can take this issue.

**Comment by arpit456jain** [comment]
No i had not commented it for taking it up😅 i was asking because we have a plan to migrate this project into django soon so i am waiting for all PRs got merged 🙂

@ankitapuri i think you can add label for up for grabs :)
