### ISSUE TITLE
Selecting different color

### ISSUE THREAD

**Issue by Aarti002** [FOSS-Cell-GECPKD/pixelvibe#145]
Providing option to user to select variety of colors.
Please @ankitapuri assign me this issue 
Thank you!

**Comment by ankitapuri** [comment]
> Providing option to user to select variety of colors.
> Please @ankitapuri assign me this issue
> Thank you!

We already have the color palette

**Comment by Aarti002** [comment]
but we can't select them i mean they don't work i guess @ankitapuri

**Comment by ankitapuri** [comment]
Check it now its working

**Comment by Aarti002** [comment]
but still we could select color from limited options can i add color picker?
Please assign this to me @ankitapuri 
Thank you!

**Comment by ankitapuri** [comment]
> but still we could select color from limited options can i add color picker?
> Please assign this to me @ankitapuri
> Thank you!

I am still not getting u , can u show some rough sketch regarding the same

**Comment by Aarti002** [comment]
something like this 
![Screenshot (139)](https://user-images.githubusercontent.com/70666307/117244972-a1827000-ae57-11eb-8202-36553d1be88c.png)

**Comment by Aarti002** [comment]
i hope @ankitapuri u get it now?

**Comment by ankitapuri** [comment]
Yeah , I got it ! 
But I would say lets keep the colors limited it looks decent enough
