### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by ankitapuri** [FOSS-Cell-GECPKD/pixelvibe#147]
**Screenshots**

When we enter the unequal board size like 5x4 , then the download button position doesn't show responsiveness
![image](https://user-images.githubusercontent.com/54734002/117006426-0c239680-ad06-11eb-8f1e-2c8a71d3ff44.png)

**Comment by arpit456jain** [comment]
@ankitapuri i would like to give it a try

**Comment by arpit456jain** [comment]
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> When we enter the unequal board size like 5x4 , then the download button position doesn't show responsiveness
> ![image](https://user-images.githubusercontent.com/54734002/117006426-0c239680-ad06-11eb-8f1e-2c8a71d3ff44.png)

@ankitapuri that's because in css position is absolute that's why it is not possible to make it responsive 
we can put it on top so it won't be affected by size of canvas

**Comment by ankitapuri** [comment]
> > **Screenshots**
> > If applicable, add screenshots to help explain your problem.
> > When we enter the unequal board size like 5x4 , then the download button position doesn't show responsiveness
> > ![image](https://user-images.githubusercontent.com/54734002/117006426-0c239680-ad06-11eb-8f1e-2c8a71d3ff44.png)
> 
> @ankitapuri that's because in css position is absolute that's why it is not possible to make it responsive
> we can put it on top so it won't be affected by size of canvas

where on top u suggest ?

**Comment by arpit456jain** [comment]
<img width="960" alt="download" src="https://user-images.githubusercontent.com/55352601/117328336-29489880-aeb1-11eb-9e8d-efad30f118ac.png">

@ankitapuri

**Comment by arpit456jain** [comment]
now it will not get affected by size of canvas

**Comment by arpit456jain** [comment]
@ankitapuri can i make a PR for this?

**Comment by ankitapuri** [comment]
> @ankitapuri can i make a PR for this?

yes

**Comment by arpit456jain** [comment]
@ankitapuri kindly merge my PR #153 
Since the changes are on same page I can not make simultaneously PR it will cause merge conflicts
