### ISSUE TITLE
Adjusting drop-down menu

### ISSUE THREAD

**Issue by ankitapuri** [FOSS-Cell-GECPKD/pixelvibe#148]
**Screenshots**

Shifting the drop-down menu to left side and little bit upwards.

**Comment by arpit456jain** [comment]
@ankitapuri kindly Assign me this issue

**Comment by arpit456jain** [comment]
<img width="960" alt="pix" src="https://user-images.githubusercontent.com/55352601/117287439-f9d16600-ae87-11eb-8cfb-cff426454ea5.png">
@ankitapuri  is this ok ?

**Comment by ankitapuri** [comment]
> <img alt="pix" width="960" src="https://user-images.githubusercontent.com/55352601/117287439-f9d16600-ae87-11eb-8cfb-cff426454ea5.png">
> 
> @ankitapuri is this ok ?

can u please make the drop-down menu more upwards

**Comment by arpit456jain** [comment]
<img width="960" alt="pix2" src="https://user-images.githubusercontent.com/55352601/117312917-1038eb00-aea3-11eb-9b95-292fff293bb9.png">

@ankitapuri is this fine now

**Comment by ankitapuri** [comment]
yes

**Comment by arpit456jain** [comment]
@ankitapuri here is the PR kindly add labels before  merge
