### ISSUE TITLE
Adjusting Return button

### ISSUE THREAD

**Issue by ankitapuri** [FOSS-Cell-GECPKD/pixelvibe#149]
**Screenshots**

Shifting the return button to extreme left just below the drop-down menu

**Comment by CMELAKKIA** [comment]
@ankitapuri  I would like to work on this issue

**Comment by Aarti002** [comment]
@ankitapuri can i work on this issue?
please assign this to me
Thank you!

**Comment by arpit456jain** [comment]
@ankitapuri i am also interested in this issue
