### ISSUE TITLE
Adding shadow effect to selected color

### ISSUE THREAD

**Issue by Aarti002** [FOSS-Cell-GECPKD/pixelvibe#152]
This would show which color has been selected from provided color pallets.
@ankitapuri can i work on this issue?
Thank you!

**Comment by Aarti002** [comment]
@ankitapuri i don't know why selected colors are not working i mean only black color works even after selecting other color?
Please help!
Thank you

**Comment by ankitapuri** [comment]
> @ankitapuri i don't know why selected colors are not working i mean only black color works even after selecting other color?
> Please help!
> Thank you

your forked repo is some commits behind please update it

**Comment by Aarti002** [comment]
@ankitapuri i'm facing some issues i don't know why color pallets are not working in my forked repo, please give me some time 
Thank you!

**Comment by Aarti002** [comment]
why i am not able to  fetch new changes, even after cloning again? @ankitapuri

**Comment by Aarti002** [comment]
as whole project view has been changed

**Comment by ankitapuri** [comment]
> as whole project view has been changed

we have migrated to flask

**Comment by Aarti002** [comment]
i'm not able to get new features please help @ankitapuri

**Comment by ankitapuri** [comment]
> i'm not able to get new features please help @ankitapuri

just rebase your branch , and use the commands as shown in the readme .
