### ISSUE TITLE
New Feature: Add a color input in the palette to allow user to select colors apart from the 12 standard ones

### ISSUE THREAD

**Issue by N-Shar-ma** [FOSS-Cell-GECPKD/pixelvibe#158]
## Screenshot:
![image](https://user-images.githubusercontent.com/68962290/117545273-e1716080-afd9-11eb-8d95-c86ddc5b3b1f.png)
![image](https://user-images.githubusercontent.com/68962290/117545294-fd750200-afd9-11eb-9e6c-20e77d2c82f6.png)

**Comment by ankitapuri** [comment]
@N-Shar-ma  so u will add a separate color palette down in order to select other colors ?

**Comment by N-Shar-ma** [comment]
@ankitapuri No, ony 1 input element of type color will be added as the last row in the color palette grid. Please see the first screenshot I've attached above, that is how the change will look. 

The 2nd screenshot shows how a standard input of type color works, so it shows what happens on clicking an input of type color

**Comment by ankitapuri** [comment]
> @ankitapuri No, ony 1 input element of type color will be added as the last row in the color palette grid. Please see the first screenshot I've attached above, that is how the change will look.
> 
> The 2nd screenshot shows how a standard input of type color works, so it shows what happens on clicking an input of type color

yeah that's what I meant the remaining would remain same just the other one of all the variant colors

**Comment by N-Shar-ma** [comment]
So should I work on this? @ankitapuri
