### ISSUE TITLE
Grid not displaying on clicking submit 

### ISSUE THREAD

**Issue by ankitapuri** [FOSS-Cell-GECPKD/pixelvibe#16]
The grid is not displayed when we click submit button .

**Comment by DharmikPansuriya** [comment]
Hello @ankitapuri,
Can you please elaborate on this issue? As, Grid is displayed in my local system, after clicking submit button!

**Comment by ankitapuri** [comment]
> Hello @ankitapuri,
> Can you please elaborate on this issue? As, Grid is displayed in my local system, after clicking submit button!

Its displaying even in my local machine but when I deploy it online then its not working .

**Comment by micksharma** [comment]
Can I work on this issue ?

**Comment by simranbhalla3** [comment]
Hii i am a gssoc participant , please assign me this issue so that i can work on it @ankitapuri

**Comment by ankitapuri** [comment]
> Can I work on this issue ?

Any progress @micksharma

**Comment by micksharma** [comment]
Yes @ankitapuri Today I submit PR.

**Comment by ankitapuri** [comment]
> Yes @ankitapuri Today I submit PR.

please submit the PR by end of day else u will be unassigned

**Comment by micksharma** [comment]
@ankitapuri  Its shows grid when I clicked on submit button. Its works fine.

**Comment by adarshvulli** [comment]
> Hii i am a gssoc participant , please assign me this issue so that i can work on it @ankitapuri

please have a look at the issue mam! u can work on it
