### ISSUE TITLE
To create a login page for users 

### ISSUE THREAD

**Issue by ankitapuri** [FOSS-Cell-GECPKD/pixelvibe#17]
It will be divided in 3 parts : 
- header (which will contain the name of the project and toggle button for light n dark mode )
- main body ( where the user will have the option to signup/sign in using the mail address and password )
- footer (mentioning made with love)

**Comment by deek121477** [comment]
Hey, I would love to contribute to this issue . Could you plz assign me?

**Comment by micksharma** [comment]
Can I work on this issue ?

**Comment by Pratibha-Rawat** [comment]
Hey! Can you please assign me this issue? I am a participant at GSSOC'21.

**Comment by shairanshrawat** [comment]
I am a participant in GSSOC 2021. I want to contribute to this issue and work on the same. Please could you assign me this issue as a part of GSSOC 2021.
Thank you.

**Comment by ankitapuri** [comment]
@deek121477 you can work on header part 
@Pratibha-Rawat you can work on body 
@shairanshrawat you can work on footer 
you all can co-ordinate with each other accordingly , and before starting let's discuss in discord once .

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this. Hope to hear back from you .
The page will be divided in 3 parts
1) Header with navbar
2) Main body
3) Footer
Thank you .

**Comment by shairanshrawat** [comment]
> @deek121477 you can work on header part
> @Pratibha-Rawat you can work on body
> @shairanshrawat you can work on footer
> you all can co-ordinate with each other accordingly , and before starting let's discuss in discord once .

hey @ankitapuri 
in the discord server they haven't made a separate channel for  pixelvibe...just wanted to know how we will discuss on discord

**Comment by Abhishek765** [comment]
Hi, I want to contribute One thing Are you using Normal HTML, CSS, or any frameworks for that??

**Comment by ankitapuri** [comment]
> Hi, I want to contribute One thing Are you using Normal HTML, CSS, or any frameworks for that??

I will be creating new issues soon u can check them out

**Comment by ankitapuri** [comment]
> > @deek121477 you can work on header part
> > @Pratibha-Rawat you can work on body
> > @shairanshrawat you can work on footer
> > you all can co-ordinate with each other accordingly , and before starting let's discuss in discord once .
> 
> hey @ankitapuri
> in the discord server they haven't made a separate channel for pixelvibe...just wanted to know how we will discuss on discord

They will soon set it up because that's the only place where we can discuss .

**Comment by Aarti002** [comment]
hello  @ankitapuri  i'm a GSSoC participant can i work on this issue?

**Comment by Aarti002** [comment]
or any similer type of issue related to frontend work  i'm ok with that too.

**Comment by ankitapuri** [comment]
> > > @deek121477 you can work on header part
> > > @Pratibha-Rawat you can work on body
> > > @shairanshrawat you can work on footer
> > > you all can co-ordinate with each other accordingly , and before starting let's discuss in discord once .
> > 
> > 
> > hey @ankitapuri
> > in the discord server they haven't made a separate channel for pixelvibe...just wanted to know how we will discuss on discord
> 
> They will soon set it up because that's the only place where we can discuss .

can u guys dm me in discord once 
My username is: Ankita#5851

**Comment by simranbhalla3** [comment]
Hii @ankitapuri Can i work on this issue as a gssoc participant ? also i can work on any other issue related to frontend

**Comment by barsha119** [comment]
Hii @ankitapuri I am a gssoc'21 participant. I want to design the sign up / sign in page. Can you please assign me this?

**Comment by Srijan205** [comment]
I want to work on this issue
