### ISSUE TITLE
Change the font-family and styling the input boxes

### ISSUE THREAD

**Issue by gnikita432** [FOSS-Cell-GECPKD/pixelvibe#18]
enhancing its styling by changing the font-family and styling the input boxes(like increasing some width and adding shadows and radius)
![i1](https://user-images.githubusercontent.com/61223163/110458563-ea38d980-80f1-11eb-8d11-7bb45fb63ffb.PNG)
![i2](https://user-images.githubusercontent.com/61223163/110458585-f02eba80-80f1-11eb-8a57-c42831606fb4.PNG)
I am a GSSOC'21 participant. Please assign me this issue under GSSOC

**Comment by Siddharth1006** [comment]
I am GSSOC21 participant. I am interested on working on this issue.

**Comment by aastha-io** [comment]
hey, i would like to work on this issue, can you please assign it to me?

**Comment by gnikita432** [comment]
hey, @ankitapuri can you please assign me this issue

**Comment by ankitapuri** [comment]
@gnikita432  there are certain changes that are more important and prior to cover before working on this . so currently its not required to work on it .

**Comment by simranbhalla3** [comment]
I am Gssoc'21 participant please assign this issue to me as i have prior knowledge of this and can work on this. @gnikita432

**Comment by Ayushbajpai19** [comment]
Hello, I would like to contribute to this issue under GSSOC'21.

**Comment by Aarti002** [comment]
hey @ankitapuri can i work on this issue i would add some animation as well . Please assign this to me
Thank you!

**Comment by ankitapuri** [comment]
> enhancing its styling by changing the font-family and styling the input boxes(like increasing some width and adding shadows and radius)
> ![i1](https://user-images.githubusercontent.com/61223163/110458563-ea38d980-80f1-11eb-8d11-7bb45fb63ffb.PNG)
> ![i2](https://user-images.githubusercontent.com/61223163/110458585-f02eba80-80f1-11eb-8a57-c42831606fb4.PNG)
> I am a GSSOC'21 participant. Please assign me this issue under GSSOC

Are u willing to do it @gnikita432

**Comment by gnikita432** [comment]
YES, @ankitapuri I would like to work on this.
