### ISSUE TITLE
Undo functionality

### ISSUE THREAD

**Issue by ankitapuri** [FOSS-Cell-GECPKD/pixelvibe#180]
**Screenshots**

To add the Undo functionality in the drop-down which could work well on canvas

**Comment by Ananya-Misra** [comment]
@ankitapuri I would like to work on this issue. Please assign this to me.

**Comment by subhangi2731** [comment]
@ankitapuri please assign me this issue

**Comment by ankitapuri** [comment]
> @ankitapuri I would like to work on this issue. Please assign this to me.

Hey Ananya , Subhangi had previously discussed with me for the issue in discord . So as of now I need to assign her , if she is stuck or unable to do I'll assign u

**Comment by subhangi2731** [comment]
@ankitapuri thankyou so much I will share u my work and make a pr

**Comment by Ananya-Misra** [comment]
Okay.

**Comment by arpit456jain** [comment]
@subhangi2731 are you working on this issue?

**Comment by subhangi2731** [comment]
@arpit456jain yes I am working on it will make a pr by tomorrow

**Comment by arpit456jain** [comment]
ok @subhangi2731 but please make sure you start working after PR 215 got merged otherwise you will face merge conflicts

**Comment by arpit456jain** [comment]
since i had moved all css to a separate file canvas.css

**Comment by subhangi2731** [comment]
@arpit456jain ohh okay i will do that after your pr gets merged

**Comment by arpit456jain** [comment]
@subhangi2731 are you working on this. Please update. Or give chances others to work on it .

**Comment by ankitapuri** [comment]
@subhangi2731 please make the PR by tomorrow , we also need to give chance to others

**Comment by subhangi2731** [comment]
@ankitapuri I am working on this but I m getting errors I am getting stuck please help me out

**Comment by subhangi2731** [comment]
@arpit456jain I am working on this but I am getting stuck for which I need some help

**Comment by arpit456jain** [comment]
@subhangi2731  You can discuss this on discord server of Pixelvibe i will try to solve your problem

**Comment by subhangi2731** [comment]
@arpit456jain thank u so much for reaching out. I will ask tomorrow morning the error which i am facing please help me out

**Comment by subhangi2731** [comment]
![image](https://user-images.githubusercontent.com/53938490/119249341-67ce9a80-bbb5-11eb-858b-bc0918c41a97.png)

**Comment by subhangi2731** [comment]
@ankitapuri @arpit456jain I am facing this error please help me not able to create virtual env

**Comment by subhangi2731** [comment]
i know how to this issue but i am not able to run and setup

**Comment by arpit456jain** [comment]
@subhangi2731 just follow these steps
1 delete your forked repo and forked it again 
2 delete copy on your system and git clone again
3 no need of making virtual env for now since we are not using any external dependency.
4 open terminal run 
Py.exe manage.py migrate
py.exe manage.py runserver

**Comment by subhangi2731** [comment]
@arpit456jain I did that it got resolved sending the pr still tysm for helping
