### ISSUE TITLE
CSS for forget password in dark mode

### ISSUE THREAD

**Issue by rupal11** [FOSS-Cell-GECPKD/pixelvibe#183]
![2021-05-14_220030](https://user-images.githubusercontent.com/60324778/118300888-0d23a780-b500-11eb-9564-1ea43da4c167.png)

When dark mode is on, the forgot password card does not reflect it. I want to solve the problem. Kindly assign it to me

**Comment by arpit456jain** [comment]
hey @rupal11 please try to complete it ASAP :)

**Comment by rupal11** [comment]
Sure. I will do it.
