### ISSUE TITLE
Optimize the repetitive code

### ISSUE THREAD

**Issue by sanjitcodes** [FOSS-Cell-GECPKD/pixelvibe#184]
**Screenshots**

To optimize the repetitive code in the file
pixelvibe/template/loader.html

![Screenshot 2021-05-15 at 3 04 16 AM](https://user-images.githubusercontent.com/59444668/118333957-4cff8480-b52a-11eb-890d-22365aae818e.png)
![Screenshot 2021-05-15 at 3 04 29 AM](https://user-images.githubusercontent.com/59444668/118333967-50930b80-b52a-11eb-90c4-249512a02e38.png)

**Comment by sanjitcodes** [comment]
I would like to work on this issue. Kindly assign it to me as a part of GSSoC.
Thank you!

**Comment by ankitapuri** [comment]
We are not including this file in our webpage , its just added as an extra
