### ISSUE TITLE
Add a pull request template

### ISSUE THREAD

**Issue by kanak22** [FOSS-Cell-GECPKD/pixelvibe#19]
I would like to add a Contributing.md to this project as a part of GGSOC'21. Kindly assign it to me.

**Comment by avinal** [comment]
Hello @kanak22, we feel that Contributing.md should be added from the project maintainers' side after evaluating the demand of all types of contributors. Actually, we are already adding it(you can propose changes once it is merged.) Instead, you may want to add a pull request template or an issue template, we don't have that too. If you agree then please change the title and I will assign it to you. 
I apologize for not synchronizing our changes with issues. Thanks

**Comment by kanak22** [comment]
I did 🤗 kindly assign it to me

**Comment by avinal** [comment]
If you need some help with the content of the template, do ask 👍🏼. I think a basic template with some customization will be fine.

**Comment by kanak22** [comment]
Sure 🤗
