### ISSUE TITLE
Dark mode in home page with new and responsive toggle button

### ISSUE THREAD

**Issue by arpit456jain** [FOSS-Cell-GECPKD/pixelvibe#200]
Dark mode in home page with new and responsive toggle button

**Comment by arpit456jain** [comment]
@ankitapuri please assign me this issue

**Comment by ankitapuri** [comment]
> Dark mode in home page with new and responsive toggle button

can u show the toggle button which u are actually using ?

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/118492514-b60b1600-b73d-11eb-8f36-e625a864b3de.mp4

@ankitapuri
