### ISSUE TITLE
When the grid height is large, whole grid is not visible and there is no scroll bar.

### ISSUE THREAD

**Issue by kanishka8276** [FOSS-Cell-GECPKD/pixelvibe#22]
When the grid height is large, whole grid is not visible. And also there is no scroll bar.
Please assign this to me. @ankitapuri 
#GsSOC'21

**Comment by ankitapuri** [comment]
The webpage is currently in making and at this stage there are certain tasks which r going on . we would reconsider this at a later stage after we atleast have the base of the pages .
