### ISSUE TITLE
Add a custom scrollbar

### ISSUE THREAD

**Issue by saatviknagpal** [FOSS-Cell-GECPKD/pixelvibe#223]
I would like to add a custom scrollbar that will match the color of the navbar and the background of the homepage.
If needed, I can add a scrollbar to the canvas section too.
Kindly assign this issue to me.

**Screenshots**
![Screenshot (30)](https://user-images.githubusercontent.com/61618767/118805787-f4324200-b8c3-11eb-8c64-2edcc0d4235f.png)

**Comment by rupal11** [comment]
Don't you think, the scroll bar will be indistinguishable because the gif is also of same color. Why not, try different color?

**Comment by saatviknagpal** [comment]
@rupal11 yeah you're right, what color do you suggest then?

**Comment by rupal11** [comment]
grey, #DDA6A2(create a gradient from light to dark, it will look good), #339EA6,#FADA7C

Try different color and which ever suits, use it.

**Comment by saatviknagpal** [comment]
but then it would look like a normal scrollbar

**Comment by rupal11** [comment]
I have added more colors.

**Comment by saatviknagpal** [comment]
Alright, Thanks!
