### ISSUE TITLE
PEP8 standards 

### ISSUE THREAD

**Issue by ankitapuri** [FOSS-Cell-GECPKD/pixelvibe#246]
**Screenshots**

Mention in the readme about the PEP8 standards that contributors must follow

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by ankitapuri** [comment]
@AshuKV are u working on it ?

**Comment by AshuKV** [comment]
> @AshuKV are u working on it ?

I am working on it, will send a PR soon.

**Comment by ankitapuri** [comment]
> > @AshuKV are u working on it ?
> 
> I am working on it, will send a PR by tomorrow.

I have already assigned u 4 days back , please try doing it asap .
