### ISSUE TITLE
Add an issue template 

### ISSUE THREAD

**Issue by kanak22** [FOSS-Cell-GECPKD/pixelvibe#25]
I would like to add an issue template for the project as a part of GSSOC'21. Kindly assign it to me.

**Comment by ankitapuri** [comment]
Just add a basic default template for creating issues . 
Will u be able be able to do @kanak22

**Comment by kanak22** [comment]
A pr template? Yes I can

**Comment by kanak22** [comment]
Actually I just did that pr template yesterday..today it was merged by you!

**Comment by ankitapuri** [comment]
> Actually I just did that pr template yesterday..today it was merged by you!

sorry the issues one

**Comment by kanak22** [comment]
Yeah sure I can
