### ISSUE TITLE
Set default canvas size

### ISSUE THREAD

**Issue by subhangi2731** [FOSS-Cell-GECPKD/pixelvibe#263]
The placeholder text is in dark, so it seems pre-filled, but which isn't. users click on submit and then get a message to enter value in textboxes. so, instead of placeholder, set default value as 16 in textbox. on submit, a canvas with 16*16 size should be created.
![Screenshot from 2021-05-23 10-51-43](https://user-images.githubusercontent.com/53938490/119251266-6efca500-bbc3-11eb-9f40-215b981e6ce7.png)

**Comment by subhangi2731** [comment]
@ankitapuri please assign this issue to me. I want to work on this

**Comment by arpit456jain** [comment]
@subhangi2731 as of now , user can't go to canvas page without entering height and width . so no need of giving default size

**Comment by subhangi2731** [comment]
ohh ok @arpit456jain i will close this issue

**Comment by arpit456jain** [comment]
@subhangi2731 can you add a feature in canvas page of Changing brush size ??
Or any other feature ?

**Comment by subhangi2731** [comment]
@arpit456jain sure i can do that I will go for it then thanks for suggesting
