### ISSUE TITLE
Show current color

### ISSUE THREAD

**Issue by subhangi2731** [FOSS-Cell-GECPKD/pixelvibe#268]
show the currently selected color in "pick a color". currently selected brush colour is not displayed so to display that I want to work

**Comment by subhangi2731** [comment]
@ankitapuri please assign this issue to me

**Comment by ankitapuri** [comment]
@subhangi2731 , can u please explain , what will you add in this

**Comment by subhangi2731** [comment]
@ankitapuri I will add a square which will show the currently selected colour and then the above please assign me

**Comment by ankitapuri** [comment]
@subhangi2731 r u working on it ?

**Comment by subhangi2731** [comment]
@ankitapuri yes doing this will send a pr
