### ISSUE TITLE
Improvement of the Home-page and adding the bullet items in the home-page

### ISSUE THREAD

**Issue by GurleenKaur111** [FOSS-Cell-GECPKD/pixelvibe#29]
I would like to add the list and the bullet items in the home-page and make it more attractive by adding other features in the home-page. Can you please assign this task to me?

**Comment by ankitapuri** [comment]
> I would like to add the list and the bullet items in the home-page and make it more attractive by adding other features in the home-page. Can you please assign this task to me?

Can u explain in detail a bit about it
