### ISSUE TITLE
Add the labels in the Readme.md 

### ISSUE THREAD

**Issue by ankitapuri** [FOSS-Cell-GECPKD/pixelvibe#30]
Add labels in the Readme displaying 
- No of contributors 
- Issues opened 
- Issues closed 
- PRs open
- PRs closed
- Repo Size
- Built By developers 
- Built with Love

**Comment by SHAIMA-HAQUE** [comment]
Hi!
I would like to work on this.
Could you please assign it to me

**Comment by SHAIMA-HAQUE** [comment]
I have made the PR. Please check
