### ISSUE TITLE
project cover design

### ISSUE THREAD

**Issue by adarshvulli** [FOSS-Cell-GECPKD/pixelvibe#33]
Create a design for the readme. md

Size:  width=200  height=400

Theme: pixel-art in sync to the pixel vibe

**Comment by adarshvulli** [comment]
please send a sketch here or over the discord channel before making the pr! 😃

**Comment by av-0901** [comment]
I can do this stuff. I am a GSSoC participant . Kindly provide me this issue.

**Comment by aditisneh** [comment]
Hey , if there's multiple contribution required, I can add a cool banner/gif to the readme along with neon effects, basically making the readme attractive. Am a GSSCO21 participant.  I will be sending the demo out here in a while. Do check.

**Comment by adarshvulli** [comment]
hey @av-0901, so it's been 2 days. can I get an update so far made?

**Comment by adarshvulli** [comment]
> Hey , if there's multiple contribution required, I can add a cool banner/gif to the readme along with neon effects, basically making the readme attractive. Am a GSSCO21 participant. I will be sending the demo out here in a while. Do check.

hey @aditisneh, can you make a separate issue ! by following the template.

**Comment by aditisneh** [comment]
@adarshvulli okay then, means that you will review my PR , if it suits you then you will directly merge it. Right?

**Comment by adarshvulli** [comment]
> @adarshvulli okay then, means that you will review my PR , if it suits you then you will directly merge it. Right?

i mean can u raise a new issue so there we can discuss!

**Comment by aditisneh** [comment]
@adarshvulli sure :)
