### ISSUE TITLE
Design the home page

### ISSUE THREAD

**Issue by nandini2110** [FOSS-Cell-GECPKD/pixelvibe#36]
I would like to make the following improvement on the home page:
 *Add a header section that would comprise of options like start drawing and login/signup
 *In the body section, give a short description of the website and few artworks made 
 *Add a start drawing button that will redirect the user to the pixel art page

**Comment by ankitapuri** [comment]
> I would like to make the following improvement on the home page:
> *Add a header section that would comprise of options like start drawing and login/signup
> *In the body section, give a short description of the website and few artworks made
> *Add a start drawing button that will redirect the user to the pixel art page

The webpage is currently in making and at this stage there are certain tasks which r going on . we would reconsider this at a later stage after we atleast have the base of the pages .
