### ISSUE TITLE
Adding a scroll bar to the home page 

### ISSUE THREAD

**Issue by kanak22** [FOSS-Cell-GECPKD/pixelvibe#37]
I would like to add a scroll bar to the home page as if the user enters 20 by 20 grid it isnt completely visible and there arent any ways to scroll down and see it. Kindly assign it to me as a part of GGSOC'21..

**Screenshots**

**Comment by ankitapuri** [comment]
The webpage is currently in making and at this stage there are certain tasks which r going on . we would reconsider this at a later stage after we atleast have the base of the pages .
