### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by aashishah** [FOSS-Cell-GECPKD/pixelvibe#39]
I'd like to create a professional logo for the website, something that goes with the theme.

I'd like to work on this under GSSOC'21, so if you approve of the issue please assign it to me. Thank you :)

**Comment by adarshvulli** [comment]
hey @aashishah  sure u can go ahead! can you! post some ideas or things once made so that we can discuss them here or in the discord channel.

**Comment by aashishah** [comment]
> hey @aashishah sure u can go ahead! can you! post some ideas or things once made so that we can discuss them here or in the discord channel.

Surely, will post some designs here. Thank you!

**Comment by ankitapuri** [comment]
> > hey @aashishah sure u can go ahead! can you! post some ideas or things once made so that we can discuss them here or in the discord channel.
> 
> Surely, will post some designs here. Thank you!

Share it in discord server

**Comment by adarshvulli** [comment]
> > hey @aashishah sure u can go ahead! can you! post some ideas or things once made so that we can discuss them here or in the discord channel.
> 
> Surely, will post some designs here. Thank you!

yeah, please use the project discord server!

**Comment by aashishah** [comment]
> > > hey @aashishah sure u can go ahead! can you! post some ideas or things once made so that we can discuss them here or in the discord channel.
> > 
> > 
> > Surely, will post some designs here. Thank you!
> 
> yeah, please use the project discord server!

**Comment by aashishah** [comment]
I accidentally closed this, apologies!

**Comment by Ayushbajpai19** [comment]
I would also like to make logo for the website under GSSOc'21, if you approve of this issue, I will start working on it.
