### ISSUE TITLE
Sign In buttons enhancement

### ISSUE THREAD

**Issue by abhi-bhatra** [FOSS-Cell-GECPKD/pixelvibe#397]
**Summary**
Sign In buttons, like Google and Facebook had very dark labels, which makes the text unreadable.

**Actual Behaviour**

<img width="945" alt="actual" src="https://user-images.githubusercontent.com/63901956/130814187-169ec51b-20d4-4296-915d-a3003f239117.png">

**Expected Behaviour**

<img width="946" alt="expected" src="https://user-images.githubusercontent.com/63901956/130814315-fa0a9117-5f71-4120-8f85-d445fe35046e.png">

I have corrected the CSS file and the login page and will create a PR.

**Comment by ankitapuri** [comment]
@abhi-bhatra I will review it once , sorry for the delay
