### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by nirban256** [FOSS-Cell-GECPKD/pixelvibe#403]
**Screenshots**
On clicking the deployment it shows error 404: Page not found
![Screenshot from 2021-12-05 13-22-58](https://user-images.githubusercontent.com/74231771/144738444-3799872d-447c-486b-8cc1-06ab49afbc2f.png)

**Comment by ankitapuri** [comment]
Its not deployed

**Comment by nirban256** [comment]
ok
