### ISSUE TITLE
Changes in the Readme

### ISSUE THREAD

**Issue by ankitapuri** [FOSS-Cell-GECPKD/pixelvibe#406]
In the readme add about the ongoing open source program . 

**Screenshots**

**Comment by iamsandeepshekhawat** [comment]
Please assign the issue to me. and can you tell me which type of problems explain in screenshot.

**Comment by subhamgcon** [comment]
> In the readme add about the ongoing open source program .
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.

Can I add the PR for this?
