### ISSUE TITLE
Dockerize The Project

### ISSUE THREAD

**Issue by 7saikat7** [FOSS-Cell-GECPKD/pixelvibe#409]
Dockerize the project and also create proper docs for it and add it to a section of the readme.md file

**Comment by RishiKumarRay** [comment]
Hi , Assign me this i would like to work on this

**Comment by 7saikat7** [comment]
go for it !

**Comment by RishiKumarRay** [comment]
HEY , my friend worked on this , he will be creating a PR , Please do check and let us know if there's any issue

**Comment by rishvantsingh** [comment]
Yes , I have worked on it and will generate the PR right now.
