### ISSUE TITLE
Tech Stack Update ( LOGO add ) 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [FOSS-Cell-GECPKD/pixelvibe#41]
I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!

**Comment by Sandi-09** [comment]
I would like to add the logos to the readme file.Please /assign this to me as a part of GSSOC'21

**Comment by ankitapuri** [comment]
> I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!

Explain about this in the main server once .

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> > I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!
> 
> Explain about this in the main server once .

Means ?

**Comment by ankitapuri** [comment]
> > > I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!
> > 
> > 
> > Explain about this in the main server once .
> 
> Means ?

Discord server of gssoc

**Comment by rohan-kulkarni-25** [comment]
Ok
