### ISSUE TITLE
Change color of Pre-loader

### ISSUE THREAD

**Issue by ankitapuri** [FOSS-Cell-GECPKD/pixelvibe#410]
The existing color is complete pink .Change color of Pre-loader to such which matches with theme of the project. 
**Screenshots**

**Comment by AryanShinde** [comment]
Hey, I'll try to do this, will share a prototype design shortly.

**Comment by AryanShinde** [comment]
![image](https://user-images.githubusercontent.com/73652194/146507738-db09ba6c-d318-4231-8280-3d51a0328825.png)

Hey, This is how it looks, I have also made it a bit responsive for mobile devices and resolved a problem related to the overflowing of certain elements.
If it's good to go, I'll push it right away.

**Comment by ankitapuri** [comment]
@AryanShinde can u please delete one shade of pink bcoz its too much pinkish now

**Comment by AryanShinde** [comment]
![image](https://user-images.githubusercontent.com/73652194/146564264-e30976ef-52f4-432d-b5ee-dab66bd38bc5.png)
How 'bout this? @ankitapuri

**Comment by 7saikat7** [comment]
@AryanShinde just a suggestion, try adding green in place of that yellow box or
 else it's looking fine

**Comment by AryanShinde** [comment]
![image](https://user-images.githubusercontent.com/73652194/146588225-9a47abb2-172b-4489-aa6a-f98adb130890.png)
    
![image](https://user-images.githubusercontent.com/73652194/146587970-f1f15d1a-88cc-4962-a592-75978654b7c3.png)
which one Should I push then? @ankitapuri @7saikat7

**Comment by ankitapuri** [comment]
green one @AryanShinde
