### ISSUE TITLE
cannot sign with google and facebook

### ISSUE THREAD

**Issue by gayatrisingh31** [FOSS-Cell-GECPKD/pixelvibe#415]
when we sign with google  this project show us DoesNotExist at /accounts/google/login/
and second issue is sign with facebook when we sign with facebook it show us DoesNotExist at /accounts/facebook/login/
may I resolve this issues?

**Comment by ankitapuri** [comment]
@gayatrisingh31 sign in with google is working try doing it again by forking in once again . And facebook one is not done yet.
