### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [FOSS-Cell-GECPKD/pixelvibe#42]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by avinal** [comment]
Hello @rohank2502, thanks for opening this issue. But we don't think there is a need for adding contributors list to the readme. Although it has been followed widely, it just makes readme more cluttered and people may miss important points. I hope you understand. Please open some issue that directly benefits the project.

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Hello @rohank2502, thanks for opening this issue. But we don't think there is a need for adding contributors list to the readme. Although it has been followed widely, it just makes readme more cluttered and people may miss important points. I hope you understand. Please open some issue that directly benefits the project.

Ook For sure I will think of it !!
