### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by Rimpi246** [FOSS-Cell-GECPKD/pixelvibe#43]
**Add favicon**
I would like to add a favicon.Please `/assign` this to me as a part of GSSOC'21

**Comment by richakumari19** [comment]
I'm the participant in GSSOC'21. Could you please assign me this.I would love working on this.

**Comment by adarshvulli** [comment]
hey! can you briefly discuss the issue over the main server!

**Comment by theSatvik** [comment]
I'm a participant in GSSOC'21. Could you please assign me this? I would love to work on this.

**Comment by ankitapuri** [comment]
> I'm a participant in GSSOC'21. Could you please assign me this? I would love to work on this.

can u share some sample designs or ideas in discord .

**Comment by cryptofox17** [comment]
If no one is assigned, could I work on this?

**Comment by kavita1403** [comment]
Participant of GSSOC'21, I'm very much interested to work on it . Could you please give me opportunity to prove the skill that I have ?. Please assign me this, I genuinely want to work on it.

**Comment by ankitapuri** [comment]
> > I'm a participant in GSSOC'21. Could you please assign me this? I would love to work on this.
> 
> can u share some sample designs or ideas in discord .

**Anyone who is interested in this just show any design idea once in discord server**
