### ISSUE TITLE
Integrate welcome bot

### ISSUE THREAD

**Issue by fomalhauting** [FOSS-Cell-GECPKD/pixelvibe#45]
**Screenshots**
I would like to add welcome bot for first issue, first pull request, etc.
Kindly assign it to me under gssoc. Thank you

**Comment by richakumari19** [comment]
I'm the participant in GSSOC'21. Could you please assign me this.I would love working on this.

**Comment by ankitapuri** [comment]
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> I would like to add welcome bot for first issue, first pull request, etc.
> Kindly assign it to me under gssoc. Thank you

what all are u planning to include ?

**Comment by fomalhauting** [comment]
@ankitapuri A welcome bot to motivate and encourage first time issue and pull request openers. And also celebrate their first merged request.
Kindly assign it to me. Thank you!
