### ISSUE TITLE
enhancing readme

### ISSUE THREAD

**Issue by aditisneh** [FOSS-Cell-GECPKD/pixelvibe#46]
We need to depart our project objective and working , efficiently. For this we need better UI in readme also some contribution guidelines.

**Comment by adarshvulli** [comment]
so far! the contribution guidelines are added as separate, file! so apart from that how best are u suggesting to modify the present readme.
 my discord username. adarsh#3407

**Comment by aditisneh** [comment]
Hey, I didn't found you on discord, if you can search me Aditi(P)#3051
I was saying to add a poster/banner more like a logo for pixelvibe. Or else a gif on spreading colors and stuffs. Try connecting on Discord for now. I can't find any link for this server. Otherwise will upload here

**Comment by adarshvulli** [comment]
yes I get that logo and banner were assigned to other participants. earlier you told me you will be designing some neon effects for the readme so I was talking about those can you show me some of your earlier work of the same


Sure will connect on discord!

**Comment by adarshvulli** [comment]
@aditisneh I would like you to work on the issue!

**Comment by aditisneh** [comment]
@adarshvulli okay thanks
