### ISSUE TITLE
Imporoving grid visibility as per user input

### ISSUE THREAD

**Issue by poojapaliwal** [FOSS-Cell-GECPKD/pixelvibe#48]
I would like to solve the issue. When the user gives input to ow row and column, a table of the same number of rows and columns can be displayed as shown in a given figure.
![Screenshot (1)](https://user-images.githubusercontent.com/60742005/111032700-88e77200-8433-11eb-9a94-901069a1ef64.png)

but when the user enters the number of rows more than 7, only 7 rows are displayed in a table as given below.
![Screenshot (2)_LI](https://user-images.githubusercontent.com/60742005/111032849-496d5580-8434-11eb-95de-02da78fc76d2.jpg)

I would like to work on this problem as a GSSOC participant. kindly assign this issue to me. :)

**Comment by ankitapuri** [comment]
> I would like to solve the issue. When the user gives input to ow row and column, a table of the same number of rows and columns can be displayed as shown in a given figure.
> ![Screenshot (1)](https://user-images.githubusercontent.com/60742005/111032700-88e77200-8433-11eb-9a94-901069a1ef64.png)
> 
> but when the user enters the number of rows more than 7, only 7 rows are displayed in a table as given below.
> ![Screenshot (2)_LI](https://user-images.githubusercontent.com/60742005/111032849-496d5580-8434-11eb-95de-02da78fc76d2.jpg)
> 
> I would like to work on this problem as a GSSOC participant. kindly assign this issue to me. :)

The grid is not visible when u host it online

**Comment by poojapaliwal** [comment]
I have just run it locally and found this issue. 
can you explain more about the issue I should work on?

**Comment by ankitapuri** [comment]
> I have just run it locally and found this issue.
> can you explain more about the issue I should work on?

can we please discuss in server

**Comment by poojapaliwal** [comment]
> > I have just run it locally and found this issue.
> > can you explain more about the issue I should work on?
> 
> can we please discuss in server

yeah, sure! 👍

**Comment by ankitapuri** [comment]
> > > I have just run it locally and found this issue.
> > > can you explain more about the issue I should work on?
> > 
> > 
> > can we please discuss in server
> 
> yeah, sure! 👍

@poojapaliwal I'm closing this issue . A separate issue will be created by mentors n assigned to u
