### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [FOSS-Cell-GECPKD/pixelvibe#52]
Hey! I would like to add the following in contributing.md
1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
I would like to work on this issue as a part of GSSOC'21

**Comment by ankitapuri** [comment]
This is not needed in the contributing.md
