### ISSUE TITLE
Unable to scroll and bottom padding 

### ISSUE THREAD

**Issue by Alik-Kumar-Ghosh** [FOSS-Cell-GECPKD/pixelvibe#54]
This issue is related to unable to scroll and the bottom padding to last grid.

I am a GSSOC'21 participant please assign this issue to me i would like to in this issue. 

**Screenshots**

![image](https://user-images.githubusercontent.com/33929979/111070442-c9a8bf00-84f7-11eb-85d2-24234f32671a.png)

**Comment by Srijan205** [comment]
Please assign this to me i am a participant of GSSOC'21
