### ISSUE TITLE
grid visibility when deployed over GitHub pages

### ISSUE THREAD

**Issue by adarshvulli** [FOSS-Cell-GECPKD/pixelvibe#57]
**Screenshots**
![image](https://user-images.githubusercontent.com/43677033/111099976-ab30db00-856c-11eb-9c7f-bd4bb8a95772.png)
the grid is not being shown after the input size of the grid is entered.

Link:
https://foss-cell-gecpkd.github.io/pixelvibe/

**Comment by poojapaliwal** [comment]
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/43677033/111099976-ab30db00-856c-11eb-9c7f-bd4bb8a95772.png)
> the grid is not being shown after the input size of the grid is entered.
> 
> Link:
> https://foss-cell-gecpkd.github.io/pixelvibe/

As a GSSOC'21 participant, I would like to work on this issue, kindly assign this to me. :)
