### ISSUE TITLE
Adding a Homepage

### ISSUE THREAD

**Issue by ShambhaviSharma0110** [FOSS-Cell-GECPKD/pixelvibe#68]
**Screenshots**
I would like to add a homepage to this website that describes the purpose and a few other details about this website.
we can also add a navbar that can contain links which can be routed.
(Prefer to use React.js)

**Comment by ankitapuri** [comment]
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> I would like to add a homepage to this website that describes the purpose and a few other details about this website.
> we can also add a navbar that can contain links which can be routed.
> (Prefer to use React.js)

Can u please provide a rough wireframe for the same . Share it on discord if possible

**Comment by ShambhaviSharma0110** [comment]
https://www.figma.com/file/PoXsYBixFOPRauVwcYKECW/wireframe?node-id=0%3A1
This is the link to a rough wireframe I would also like to add specific pages for each section and also make an error page...

**Comment by ankitapuri** [comment]
> https://www.figma.com/file/PoXsYBixFOPRauVwcYKECW/wireframe?node-id=0%3A1
> This is the link to a rough wireframe I would also like to add specific pages for each section and also make an error page...

Add login button in the navbar also . Rest all is good to go

**Comment by ShambhaviSharma0110** [comment]
Thank you! I will start working on it

**Comment by ankitapuri** [comment]
@ShambhaviSharma0110 can you please provide the updates.

**Comment by ShambhaviSharma0110** [comment]
@ankitapuri hey! I've made separate files of the pages and added them in the folder so now the homepage appears as it was and one is directed to those pages only when the link is clicked on the navbar.

**Comment by arpit456jain** [comment]
@ShambhaviSharma0110 are you working on this issue?

**Comment by ankitapuri** [comment]
> @ShambhaviSharma0110 are you working on this issue?

she made a PR , but some changes are required which she needs to do

**Comment by SnehaVeerakumar** [comment]
@ankitapuri I would like to work on this issue. If assigned i will complete it within 3 days.

**Comment by ankitapuri** [comment]
> @ankitapuri I would like to work on this issue. If assigned i will complete it within 3 days.

I hope u know it is need to be done in separate files. Not including in the existing ones

**Comment by SnehaVeerakumar** [comment]
> > @ankitapuri I would like to work on this issue. If assigned i will complete it within 3 days.
> 
> I hope u know it is need to be done in separate files. Not including in the existing ones

Do you mean, build from scratch?

**Comment by ankitapuri** [comment]
> > > @ankitapuri I would like to work on this issue. If assigned i will complete it within 3 days.
> > 
> > 
> > I hope u know it is need to be done in separate files. Not including in the existing ones
> 
> Do you mean, build from scratch?

we don't have an existing homepage right , so its from scratch . U just include a navbar which could direct to other pages

**Comment by SnehaVeerakumar** [comment]
> > > > @ankitapuri I would like to work on this issue. If assigned i will complete it within 3 days.
> > > 
> > > 
> > > I hope u know it is need to be done in separate files. Not including in the existing ones
> > 
> > 
> > Do you mean, build from scratch?
> 
> we don't have an existing homepage right , so its from scratch . U just include a navbar which could direct to other pages

That's great. Please assign me to start working. I will keep updating about my progress. I am actually searching for issues which needs to be built from scratch.

**Comment by SnehaVeerakumar** [comment]
> > > > @ankitapuri I would like to work on this issue. If assigned i will complete it within 3 days.
> > > 
> > > 
> > > I hope u know it is need to be done in separate files. Not including in the existing ones
> > 
> > 
> > Do you mean, build from scratch?
> 
> we don't have an existing homepage right , so its from scratch . U just include a navbar which could direct to other pages

As I am currently done with all my assigned issues, I can give all my time for this project

**Comment by ankitapuri** [comment]
> > > > > @ankitapuri I would like to work on this issue. If assigned i will complete it within 3 days.
> > > > 
> > > > 
> > > > I hope u know it is need to be done in separate files. Not including in the existing ones
> > > 
> > > 
> > > Do you mean, build from scratch?
> > 
> > 
> > we don't have an existing homepage right , so its from scratch . U just include a navbar which could direct to other pages
> 
> As I am currently done with all my assigned issues, I can give all my time for this project

cool ! so I create a level 3 issue for the same . Is it fine for u

**Comment by SnehaVeerakumar** [comment]
@ankitapuri  level is not an issue :)

**Comment by arpit456jain** [comment]
> @ankitapuri I would like to work on this issue. If assigned i will complete it within 3 days.

@SnehaVeerakumar are you working on this issue ??

**Comment by SnehaVeerakumar** [comment]
> > @ankitapuri I would like to work on this issue. If assigned i will complete it within 3 days.
> 
> @SnehaVeerakumar are you working on this issue ??

Yeah, I am done and today I am about to send PR.

**Comment by SnehaVeerakumar** [comment]
@ankitapuri Please merge #139 if it is ready as I need to write few lines of code for each skin color

**Comment by arpit456jain** [comment]
> @ankitapuri Please merge #139 if it is ready as I need to write few lines of code for each skin color

@SnehaVeerakumar I think @ankitapuri asked to make a home page from scratch  having navbar and some more details related to Project 
I checked this PR #139,  he added some features in current index.html I don't think so we should make this file like a home page.

2. Its already very messed up on index.html every element having position absolute , not at all Responsive , the more content it have , more will be the issues with responsiveness
@ankitapuri please review my thoughts

**Comment by SnehaVeerakumar** [comment]
> > @ankitapuri Please merge #139 if it is ready as I need to write few lines of code for each skin color
> 
> @SnehaVeerakumar I think @ankitapuri asked to make a home page from scratch having navbar and some more details related to Project
> I checked this PR #139, he added some features in current index.html I don't think so we should make this file like a home page.
> 
> 1. Its already very messed up on index.html every element having position absolute , not at all Responsive , the more content it have , more will be the issues with responsiveness
>    @ankitapuri please review my thoughts

I have checked #139 and it's absolutely perfect and fits in my work !! I see no issues with responsiveness and what do you refer as a mess ? It was pretty simple to integrate with my code !! 
Can you exactly point out which part is a mess, so that it becomes easy to rectify ?

**Comment by ankitapuri** [comment]
> > @ankitapuri Please merge #139 if it is ready as I need to write few lines of code for each skin color
> 
> @SnehaVeerakumar I think @ankitapuri asked to make a home page from scratch having navbar and some more details related to Project
> I checked this PR #139, he added some features in current index.html I don't think so we should make this file like a home page.
> 
> 1. Its already very messed up on index.html every element having position absolute , not at all Responsive , the more content it have , more will be the issues with responsiveness
>    @ankitapuri please review my thoughts

Firstly , We will format the code once and then accordingly will take up the canvas on separate files

**Comment by ankitapuri** [comment]
> > > @ankitapuri Please merge #139 if it is ready as I need to write few lines of code for each skin color
> > 
> > 
> > @SnehaVeerakumar I think @ankitapuri asked to make a home page from scratch having navbar and some more details related to Project
> > I checked this PR #139, he added some features in current index.html I don't think so we should make this file like a home page.
> > 
> > 1. Its already very messed up on index.html every element having position absolute , not at all Responsive , the more content it have , more will be the issues with responsiveness
> >    @ankitapuri please review my thoughts
> 
> I have checked #139 and it's absolutely perfect and fits in my work !! I see no issues with responsiveness and what do you refer as a mess ? It was pretty simple to integrate with my code !!
> Can you exactly point out which part is a mess, so that it becomes easy to rectify ?

there are some code lines which are written unnecessary so , I already have created a issue on code formatting and one of the participant is working on it

**Comment by arpit456jain** [comment]
> > > @ankitapuri Please merge #139 if it is ready as I need to write few lines of code for each skin color
> > 
> > 
> > @SnehaVeerakumar I think @ankitapuri asked to make a home page from scratch having navbar and some more details related to Project
> > I checked this PR #139, he added some features in current index.html I don't think so we should make this file like a home page.
> > 
> > 1. Its already very messed up on index.html every element having position absolute , not at all Responsive , the more content it have , more will be the issues with responsiveness
> >    @ankitapuri please review my thoughts
> 
> I have checked #139 and it's absolutely perfect and fits in my work !! I see no issues with responsiveness and what do you refer as a mess ? It was pretty simple to integrate with my code !!
> Can you exactly point out which part is a mess, so that it becomes easy to rectify ?



https://user-images.githubusercontent.com/55352601/117329990-d839a400-aeb2-11eb-8f04-d95a5544c263.mp4

@SnehaVeerakumar @ankitapuri  this is the video in which i download the code of that PR and just have a look on 2nd page after the submitting the canvas size

**Comment by ankitapuri** [comment]
> > > > @ankitapuri Please merge #139 if it is ready as I need to write few lines of code for each skin color
> > > 
> > > 
> > > @SnehaVeerakumar I think @ankitapuri asked to make a home page from scratch having navbar and some more details related to Project
> > > I checked this PR #139, he added some features in current index.html I don't think so we should make this file like a home page.
> > > 
> > > 1. Its already very messed up on index.html every element having position absolute , not at all Responsive , the more content it have , more will be the issues with responsiveness
> > >    @ankitapuri please review my thoughts
> > 
> > 
> > I have checked #139 and it's absolutely perfect and fits in my work !! I see no issues with responsiveness and what do you refer as a mess ? It was pretty simple to integrate with my code !!
> > Can you exactly point out which part is a mess, so that it becomes easy to rectify ?
> 
>  2021-05-06.21-31-46.mp4 
> @SnehaVeerakumar @ankitapuri this is the video in which i download the code of that PR and just have a look on 2nd page after the submitting the canvas size

Can you share this video in her PR once .

**Comment by arpit456jain** [comment]
@SnehaVeerakumar can you share some ss or videos of your code ? It will be very helpful for understanding what changes you have done

**Comment by arpit456jain** [comment]
> > > > > @ankitapuri Please merge #139 if it is ready as I need to write few lines of code for each skin color
> > > > 
> > > > 
> > > > @SnehaVeerakumar I think @ankitapuri asked to make a home page from scratch having navbar and some more details related to Project
> > > > I checked this PR #139, he added some features in current index.html I don't think so we should make this file like a home page.
> > > > 
> > > > 1. Its already very messed up on index.html every element having position absolute , not at all Responsive , the more content it have , more will be the issues with responsiveness
> > > >    @ankitapuri please review my thoughts
> > > 
> > > 
> > > I have checked #139 and it's absolutely perfect and fits in my work !! I see no issues with responsiveness and what do you refer as a mess ? It was pretty simple to integrate with my code !!
> > > Can you exactly point out which part is a mess, so that it becomes easy to rectify ?
> > 
> > 
> > 2021-05-06.21-31-46.mp4
> > @SnehaVeerakumar @ankitapuri this is the video in which i download the code of that PR and just have a look on 2nd page after the submitting the canvas size
> 
> Can you share this video in her PR once .

yeah sure why not

**Comment by ankitapuri** [comment]
> > > > @ankitapuri Please merge #139 if it is ready as I need to write few lines of code for each skin color
> > > 
> > > 
> > > @SnehaVeerakumar I think @ankitapuri asked to make a home page from scratch having navbar and some more details related to Project
> > > I checked this PR #139, he added some features in current index.html I don't think so we should make this file like a home page.
> > > 
> > > 1. Its already very messed up on index.html every element having position absolute , not at all Responsive , the more content it have , more will be the issues with responsiveness
> > >    @ankitapuri please review my thoughts
> > 
> > 
> > I have checked #139 and it's absolutely perfect and fits in my work !! I see no issues with responsiveness and what do you refer as a mess ? It was pretty simple to integrate with my code !!
> > Can you exactly point out which part is a mess, so that it becomes easy to rectify ?
> 
>  2021-05-06.21-31-46.mp4 
> @SnehaVeerakumar @ankitapuri this is the video in which i download the code of that PR and just have a look on 2nd page after the submitting the canvas size

really grateful to u , for pointing out the error

**Comment by arpit456jain** [comment]
No problem 👍

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/117408345-6e121500-af2d-11eb-8b5a-e1f3120708db.mp4

@ankitapuri I have made this home page for this project.
Its built from scratch and totally independent of other pages . Its a basic layout lots of enhancements can be done later
I would like to make a PR for this

**Comment by SnehaVeerakumar** [comment]
> @SnehaVeerakumar can you share some ss or videos of your code ? It will be very helpful for understanding what changes you have done

Sure. Directly I will add it in a PR

**Comment by SnehaVeerakumar** [comment]
>  2021-05-07.12-11-28.mp4 
> @ankitapuri I have made this home page for this project.
> Its built from scratch and totally independent of other pages . Its a basic layout lots of enhancements can be done later
> I would like to make a PR for this

@ankitapuri I don't think it is good to encourage someone who is not assigned to make a PR. I am active here and I was just waiting for #139 to get merged as i have coded for that as well.
Shall I make a PR by removing skin colors ?

**Comment by arpit456jain** [comment]
> > 2021-05-07.12-11-28.mp4
> > @ankitapuri I have made this home page for this project.
> > Its built from scratch and totally independent of other pages . Its a basic layout lots of enhancements can be done later
> > I would like to make a PR for this
> 
> @ankitapuri I don't think it is good to encourage someone who is not assigned to make a PR. I am active here and I was just waiting for #139 to get merged as i have coded for that as well.
> Shall I make a PR by removing skin colors ?

@SnehaVeerakumar i think we need a separate page why are you waiting for that PR to be merged just start your work.

**Comment by SnehaVeerakumar** [comment]
> > > 2021-05-07.12-11-28.mp4
> > > @ankitapuri I have made this home page for this project.
> > > Its built from scratch and totally independent of other pages . Its a basic layout lots of enhancements can be done later
> > > I would like to make a PR for this
> > 
> > 
> > @ankitapuri I don't think it is good to encourage someone who is not assigned to make a PR. I am active here and I was just waiting for #139 to get merged as i have coded for that as well.
> > Shall I make a PR by removing skin colors ?
> 
> @SnehaVeerakumar i think we need a separate page why are you waiting for that PR to be merged just start your work.

That's a skin color ! Needed in home.

**Comment by ankitapuri** [comment]
@arpit456jain , I had already assigned @SnehaVeerakumar  for this issue . So before considering ur work I need to look into hers

**Comment by SnehaVeerakumar** [comment]
> @arpit456jain , I had already assigned @SnehaVeerakumar for this issue . So before considering ur work I need to look into hers

That's great, sharing my work tonight.
Tomorrow morning my PR will be all set for review. I'll temporarily add skin colors and I'll make changes after the reviewers suggestion !!

**Comment by ankitapuri** [comment]
> > @arpit456jain , I had already assigned @SnehaVeerakumar for this issue . So before considering ur work I need to look into hers
> 
> That's great, sharing my work tonight.
> Tomorrow morning my PR will be all set for review. I'll temporarily add skin colors and I'll make changes after the reviewers suggestion !!

Are making a separate page right ?

**Comment by SnehaVeerakumar** [comment]
> > > @arpit456jain , I had already assigned @SnehaVeerakumar for this issue . So before considering ur work I need to look into hers
> > 
> > 
> > That's great, sharing my work tonight.
> > Tomorrow morning my PR will be all set for review. I'll temporarily add skin colors and I'll make changes after the reviewers suggestion !!
> 
> Are making a separate page right ?

Yes it will be a fully working system with multi pages and responsiveness is checked

**Comment by SnehaVeerakumar** [comment]
@arpit456jain I am delighted to see your dedication but please allow reviewers and maintainers to give their feedback first :) 
I know you will be the first one to comment in my PR but please I request you to wait for sometime so that I can make relevant changes according to the reviewers. After that I will surely take up all your constructive critisims.

**Comment by arpit456jain** [comment]
> @arpit456jain I am delighted to see your dedication but please allow reviewers and maintainers to give their feedback first :)
> I know you will be the first one to comment in my PR but please I request you to wait for sometime so that I can make relevant changes according to the reviewers. After that I will surely take up all your constructive critisims.

@SnehaVeerakumar  I have no interest in reviewing your PR. I just no like delaying the work you are assigned on this issue 12 days ago .
I know you are waiting for that PR to be merged but its make no sense @ankitapuri  had clear asked to make a separate home page.

And you and i both know to make this home page its a 10 to 15 min work so why to delay if i had not upload that video of my work I don't think so you would create a PR
