### ISSUE TITLE
ADD proper Footer.

### ISSUE THREAD

**Issue by aashi2912** [FOSS-Cell-GECPKD/pixelvibe#71]
Want to add professional and good design of footer to the website.

Allow me as **GSSOC21** participant!
@adarshvulli @avinal @rish-singhal

**Comment by adarshvulli** [comment]
hello mam! @aashi2912 I really appreciate your interest and enthusiasm. We already assigned one of the other participants the same! So. I will close this once we are ready with the UI to raise some new issues to work on! thanks for the enthusiasm
