### ISSUE TITLE
Improvement in the UI of website.

### ISSUE THREAD

**Issue by aashi2912** [FOSS-Cell-GECPKD/pixelvibe#72]
Design and look of the website is not upto the mark. I would like to make it more attractive and enhance it's Design.

**GSSOC21**
@adarshvulli @avinal @rish-singhal

**Comment by adarshvulli** [comment]
hello mam! @aashi2912 I really appreciate your interest and enthusiasm. We already assigned one of the other participants the same! So. I will close this once we are ready with the UI to raise some new issues to work on! thanks for the enthusiasm
