### ISSUE TITLE
Adjust the board size according to the user choice 

### ISSUE THREAD

**Issue by ankitapuri** [FOSS-Cell-GECPKD/pixelvibe#82]
**Screenshots**

The form should be able to take user input and when we press submit button the canvas takes the size according to the user preference and the need .

**Comment by malavikarajeshvikraman** [comment]
Hey @ankitapuri  I think I can implement this. Could you kindly assign this to me. Basically the canvas height and width needs to be input by the user correct ?

**Comment by ankitapuri** [comment]
> Hey @ankitapuri I think I can implement this. Could you kindly assign this to me. Basically the canvas height and width needs to be input by the user correct ?

yes , but the maximum height should be such it should fit in a single screen without the need of scroller and also the width should also be limited on both sides so that utility box and colors can be added 
Would u like to work ?

**Comment by bitaashna** [comment]
@ankitapuri I would like to work on it
Can u please assign it to me.

**Comment by ankitapuri** [comment]
> @ankitapuri I would like to work on it
> Can u please assign it to me.

Are you willing to work @bitaashna

**Comment by shrishti-c** [comment]
Hey! I'm willing to work on it. Could you please assign it to me.

**Comment by bitaashna** [comment]
> > @ankitapuri I would like to work on it
> > Can u please assign it to me.
> 
> Are you willing to work @bitaashna

Yes,I am.

**Comment by ankitapuri** [comment]
@bitaashna can u please provide the updates

**Comment by athkdev** [comment]
Hi @ankitapuri, I have tried and tested the implementation for the user-defined dimensions, if you assign, I'll make the PR
