### ISSUE TITLE
Gssoc'21 Home page(index.html) is not Responsive Not Even after using Bootstrap 

### ISSUE THREAD

**Issue by arpit456jain** [FOSS-Cell-GECPKD/pixelvibe#83]
Good Evening Sir This Project is made in bootstrap but still it is not responsive In phone View it is looking like this
<img width="960" alt="pixel" src="https://user-images.githubusercontent.com/55352601/111904362-9ffa1580-8a6c-11eb-85f5-d9572d169813.png">

I would like to solve this issue and i will do it as soon as possible please assign me this issue .

**Comment by arpit456jain** [comment]
Can i start working on it??

**Comment by ankitapuri** [comment]
@arpit456jain , I suggest that first we should go with entire making of website then this part comes later . Because certainly there will be lot of transformations which are needed at this stage .

**Comment by arpit456jain** [comment]
Ok mam no problem 
I have a request @ankitapuri mam please review my PR #85  i had all the required changes which are requested by @adarshvulli sir.

**Comment by ankitapuri** [comment]
> Ok mam no problem
> I have a request @ankitapuri mam please review my PR #85 i had all the required changes which are requested by @adarshvulli sir.

I will surely do today
