### ISSUE TITLE
Want to add media query using CSS

### ISSUE THREAD

**Issue by priyanka001tech** [FOSS-Cell-GECPKD/pixelvibe#86]
As a GSSOC PARTICIPANT I want to add media query in css styling so that it looks different in phones and monitor screen.

**Comment by priyanka001tech** [comment]
please assign me

**Comment by ankitapuri** [comment]
@priyanka001tech ,I suggest that first we should go with entire making of website then this part comes later . Because certainly there will be lot of transformations which are needed at this stage .

**Comment by priyanka001tech** [comment]
okay ma'am
