### ISSUE TITLE
Adding a Clear Canvas Button

### ISSUE THREAD

**Issue by cryptofox17** [FOSS-Cell-GECPKD/pixelvibe#89]
Adding a Button to clear the canvas so that the user can start over drawing without having to refresh the page. 
It could be implemented using javascript. I would like to work on this issue

**Comment by hritikgupta92** [comment]
Please Assign this issue to me,it would be a great opportunity for me to learn about adding buttons for getting into homepage.

**Comment by ankitapuri** [comment]
we are already having one redirecting button .
