### ISSUE TITLE
Adding feature to move a step back by pressing Backspace key

### ISSUE THREAD

**Issue by sourabhkumar45** [FOSS-Cell-GECPKD/pixelvibe#90]
Users can move multiple steps back in their work by pressing backspace multiple times.

**Comment by ankitapuri** [comment]
> Users can move multiple steps back in their work by pressing backspace multiple times.

Can u please elaborate

**Comment by sourabhkumar45** [comment]
Just like letters can be removed by backspace if we write something wrong, Users can remove a mark from canvas by pressing backspace.

**Comment by ankitapuri** [comment]
For the erasing purpose we will create a utility box , which will have an eraser , also an undo feature and all clear button. So will work shortly on that . So u can try contributing there . Until then I don't think this issue has any point . 
Thanks for showing interest .
