### ISSUE TITLE
Create a button 

### ISSUE THREAD

**Issue by ankitapuri** [FOSS-Cell-GECPKD/pixelvibe#96]
**Screenshots**
Create a button which user can click and get back to the page where he can adjust the size according to the preference . 
 Ref: https://codepen.io/manelroig/pen/rJMVRO

**Comment by Anirudh-GH** [comment]
Can I try this issue?

**Comment by ankitapuri** [comment]
> Can I try this issue?

@Anirudh-GH  , Currently I have to assign this issue to someone else . As I have already discussed and explained him regarding the same .

**Comment by hritikgupta92** [comment]
@ankitapuri  Please assign it to me

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by ankitapuri** [comment]
> Can I work on this issue?

we have the PR for this

**Comment by simranbhalla3** [comment]
Hi , Can i work on this issue?

**Comment by hritikgupta92** [comment]
> Hi , Can i work on this issue?

Sorry,but I have finished the work now,and soon it would get merged
